// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MSG_DS_CS_RTABLE_SEND.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "MSG_DS_CS_RTABLE_SEND.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* MSG_DS_CS_RTABLE_SEND_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MSG_DS_CS_RTABLE_SEND_reflection_ = NULL;
const ::google::protobuf::Descriptor* MSG_DS_CS_RTABLE_SEND_ROW_TABLE_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MSG_DS_CS_RTABLE_SEND_ROW_TABLE_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_MSG_5fDS_5fCS_5fRTABLE_5fSEND_2eproto() {
  protobuf_AddDesc_MSG_5fDS_5fCS_5fRTABLE_5fSEND_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "MSG_DS_CS_RTABLE_SEND.proto");
  GOOGLE_CHECK(file != NULL);
  MSG_DS_CS_RTABLE_SEND_descriptor_ = file->message_type(0);
  static const int MSG_DS_CS_RTABLE_SEND_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSG_DS_CS_RTABLE_SEND, taskid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSG_DS_CS_RTABLE_SEND, dbid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSG_DS_CS_RTABLE_SEND, tablename_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSG_DS_CS_RTABLE_SEND, rowtable_),
  };
  MSG_DS_CS_RTABLE_SEND_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MSG_DS_CS_RTABLE_SEND_descriptor_,
      MSG_DS_CS_RTABLE_SEND::default_instance_,
      MSG_DS_CS_RTABLE_SEND_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSG_DS_CS_RTABLE_SEND, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSG_DS_CS_RTABLE_SEND, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MSG_DS_CS_RTABLE_SEND));
  MSG_DS_CS_RTABLE_SEND_ROW_TABLE_descriptor_ = MSG_DS_CS_RTABLE_SEND_descriptor_->nested_type(0);
  static const int MSG_DS_CS_RTABLE_SEND_ROW_TABLE_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSG_DS_CS_RTABLE_SEND_ROW_TABLE, columnname_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSG_DS_CS_RTABLE_SEND_ROW_TABLE, entry_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSG_DS_CS_RTABLE_SEND_ROW_TABLE, rowkey_),
  };
  MSG_DS_CS_RTABLE_SEND_ROW_TABLE_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MSG_DS_CS_RTABLE_SEND_ROW_TABLE_descriptor_,
      MSG_DS_CS_RTABLE_SEND_ROW_TABLE::default_instance_,
      MSG_DS_CS_RTABLE_SEND_ROW_TABLE_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSG_DS_CS_RTABLE_SEND_ROW_TABLE, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSG_DS_CS_RTABLE_SEND_ROW_TABLE, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MSG_DS_CS_RTABLE_SEND_ROW_TABLE));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_MSG_5fDS_5fCS_5fRTABLE_5fSEND_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MSG_DS_CS_RTABLE_SEND_descriptor_, &MSG_DS_CS_RTABLE_SEND::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MSG_DS_CS_RTABLE_SEND_ROW_TABLE_descriptor_, &MSG_DS_CS_RTABLE_SEND_ROW_TABLE::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_MSG_5fDS_5fCS_5fRTABLE_5fSEND_2eproto() {
  delete MSG_DS_CS_RTABLE_SEND::default_instance_;
  delete MSG_DS_CS_RTABLE_SEND_reflection_;
  delete MSG_DS_CS_RTABLE_SEND_ROW_TABLE::default_instance_;
  delete MSG_DS_CS_RTABLE_SEND_ROW_TABLE_reflection_;
}

void protobuf_AddDesc_MSG_5fDS_5fCS_5fRTABLE_5fSEND_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\033MSG_DS_CS_RTABLE_SEND.proto\"\274\001\n\025MSG_DS"
    "_CS_RTABLE_SEND\022\016\n\006taskID\030\001 \002(\r\022\014\n\004dbID\030"
    "\002 \002(\r\022\021\n\ttableName\030\003 \002(\t\0222\n\010rowTable\030\004 \003"
    "(\0132 .MSG_DS_CS_RTABLE_SEND.ROW_TABLE\032>\n\t"
    "ROW_TABLE\022\022\n\ncolumnName\030\001 \002(\t\022\r\n\005entry\030\002"
    " \003(\004\022\016\n\006rowKey\030\003 \003(\004", 220);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "MSG_DS_CS_RTABLE_SEND.proto", &protobuf_RegisterTypes);
  MSG_DS_CS_RTABLE_SEND::default_instance_ = new MSG_DS_CS_RTABLE_SEND();
  MSG_DS_CS_RTABLE_SEND_ROW_TABLE::default_instance_ = new MSG_DS_CS_RTABLE_SEND_ROW_TABLE();
  MSG_DS_CS_RTABLE_SEND::default_instance_->InitAsDefaultInstance();
  MSG_DS_CS_RTABLE_SEND_ROW_TABLE::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_MSG_5fDS_5fCS_5fRTABLE_5fSEND_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_MSG_5fDS_5fCS_5fRTABLE_5fSEND_2eproto {
  StaticDescriptorInitializer_MSG_5fDS_5fCS_5fRTABLE_5fSEND_2eproto() {
    protobuf_AddDesc_MSG_5fDS_5fCS_5fRTABLE_5fSEND_2eproto();
  }
} static_descriptor_initializer_MSG_5fDS_5fCS_5fRTABLE_5fSEND_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int MSG_DS_CS_RTABLE_SEND_ROW_TABLE::kColumnNameFieldNumber;
const int MSG_DS_CS_RTABLE_SEND_ROW_TABLE::kEntryFieldNumber;
const int MSG_DS_CS_RTABLE_SEND_ROW_TABLE::kRowKeyFieldNumber;
#endif  // !_MSC_VER

MSG_DS_CS_RTABLE_SEND_ROW_TABLE::MSG_DS_CS_RTABLE_SEND_ROW_TABLE()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MSG_DS_CS_RTABLE_SEND.ROW_TABLE)
}

void MSG_DS_CS_RTABLE_SEND_ROW_TABLE::InitAsDefaultInstance() {
}

MSG_DS_CS_RTABLE_SEND_ROW_TABLE::MSG_DS_CS_RTABLE_SEND_ROW_TABLE(const MSG_DS_CS_RTABLE_SEND_ROW_TABLE& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:MSG_DS_CS_RTABLE_SEND.ROW_TABLE)
}

void MSG_DS_CS_RTABLE_SEND_ROW_TABLE::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  columnname_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MSG_DS_CS_RTABLE_SEND_ROW_TABLE::~MSG_DS_CS_RTABLE_SEND_ROW_TABLE() {
  // @@protoc_insertion_point(destructor:MSG_DS_CS_RTABLE_SEND.ROW_TABLE)
  SharedDtor();
}

void MSG_DS_CS_RTABLE_SEND_ROW_TABLE::SharedDtor() {
  if (columnname_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete columnname_;
  }
  if (this != default_instance_) {
  }
}

void MSG_DS_CS_RTABLE_SEND_ROW_TABLE::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MSG_DS_CS_RTABLE_SEND_ROW_TABLE::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MSG_DS_CS_RTABLE_SEND_ROW_TABLE_descriptor_;
}

const MSG_DS_CS_RTABLE_SEND_ROW_TABLE& MSG_DS_CS_RTABLE_SEND_ROW_TABLE::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_MSG_5fDS_5fCS_5fRTABLE_5fSEND_2eproto();
  return *default_instance_;
}

MSG_DS_CS_RTABLE_SEND_ROW_TABLE* MSG_DS_CS_RTABLE_SEND_ROW_TABLE::default_instance_ = NULL;

MSG_DS_CS_RTABLE_SEND_ROW_TABLE* MSG_DS_CS_RTABLE_SEND_ROW_TABLE::New() const {
  return new MSG_DS_CS_RTABLE_SEND_ROW_TABLE;
}

void MSG_DS_CS_RTABLE_SEND_ROW_TABLE::Clear() {
  if (has_columnname()) {
    if (columnname_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
      columnname_->clear();
    }
  }
  entry_.Clear();
  rowkey_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MSG_DS_CS_RTABLE_SEND_ROW_TABLE::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MSG_DS_CS_RTABLE_SEND.ROW_TABLE)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string columnName = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_columnname()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->columnname().data(), this->columnname().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "columnname");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_entry;
        break;
      }

      // repeated uint64 entry = 2;
      case 2: {
        if (tag == 16) {
         parse_entry:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 1, 16, input, this->mutable_entry())));
        } else if (tag == 18) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, this->mutable_entry())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_entry;
        if (input->ExpectTag(24)) goto parse_rowKey;
        break;
      }

      // repeated uint64 rowKey = 3;
      case 3: {
        if (tag == 24) {
         parse_rowKey:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 1, 24, input, this->mutable_rowkey())));
        } else if (tag == 26) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, this->mutable_rowkey())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_rowKey;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MSG_DS_CS_RTABLE_SEND.ROW_TABLE)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MSG_DS_CS_RTABLE_SEND.ROW_TABLE)
  return false;
#undef DO_
}

void MSG_DS_CS_RTABLE_SEND_ROW_TABLE::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MSG_DS_CS_RTABLE_SEND.ROW_TABLE)
  // required string columnName = 1;
  if (has_columnname()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->columnname().data(), this->columnname().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "columnname");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->columnname(), output);
  }

  // repeated uint64 entry = 2;
  for (int i = 0; i < this->entry_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(
      2, this->entry(i), output);
  }

  // repeated uint64 rowKey = 3;
  for (int i = 0; i < this->rowkey_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(
      3, this->rowkey(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:MSG_DS_CS_RTABLE_SEND.ROW_TABLE)
}

::google::protobuf::uint8* MSG_DS_CS_RTABLE_SEND_ROW_TABLE::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:MSG_DS_CS_RTABLE_SEND.ROW_TABLE)
  // required string columnName = 1;
  if (has_columnname()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->columnname().data(), this->columnname().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "columnname");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->columnname(), target);
  }

  // repeated uint64 entry = 2;
  for (int i = 0; i < this->entry_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteUInt64ToArray(2, this->entry(i), target);
  }

  // repeated uint64 rowKey = 3;
  for (int i = 0; i < this->rowkey_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteUInt64ToArray(3, this->rowkey(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MSG_DS_CS_RTABLE_SEND.ROW_TABLE)
  return target;
}

int MSG_DS_CS_RTABLE_SEND_ROW_TABLE::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string columnName = 1;
    if (has_columnname()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->columnname());
    }

  }
  // repeated uint64 entry = 2;
  {
    int data_size = 0;
    for (int i = 0; i < this->entry_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        UInt64Size(this->entry(i));
    }
    total_size += 1 * this->entry_size() + data_size;
  }

  // repeated uint64 rowKey = 3;
  {
    int data_size = 0;
    for (int i = 0; i < this->rowkey_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        UInt64Size(this->rowkey(i));
    }
    total_size += 1 * this->rowkey_size() + data_size;
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MSG_DS_CS_RTABLE_SEND_ROW_TABLE::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MSG_DS_CS_RTABLE_SEND_ROW_TABLE* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MSG_DS_CS_RTABLE_SEND_ROW_TABLE*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MSG_DS_CS_RTABLE_SEND_ROW_TABLE::MergeFrom(const MSG_DS_CS_RTABLE_SEND_ROW_TABLE& from) {
  GOOGLE_CHECK_NE(&from, this);
  entry_.MergeFrom(from.entry_);
  rowkey_.MergeFrom(from.rowkey_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_columnname()) {
      set_columnname(from.columnname());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MSG_DS_CS_RTABLE_SEND_ROW_TABLE::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MSG_DS_CS_RTABLE_SEND_ROW_TABLE::CopyFrom(const MSG_DS_CS_RTABLE_SEND_ROW_TABLE& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MSG_DS_CS_RTABLE_SEND_ROW_TABLE::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void MSG_DS_CS_RTABLE_SEND_ROW_TABLE::Swap(MSG_DS_CS_RTABLE_SEND_ROW_TABLE* other) {
  if (other != this) {
    std::swap(columnname_, other->columnname_);
    entry_.Swap(&other->entry_);
    rowkey_.Swap(&other->rowkey_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MSG_DS_CS_RTABLE_SEND_ROW_TABLE::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MSG_DS_CS_RTABLE_SEND_ROW_TABLE_descriptor_;
  metadata.reflection = MSG_DS_CS_RTABLE_SEND_ROW_TABLE_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int MSG_DS_CS_RTABLE_SEND::kTaskIDFieldNumber;
const int MSG_DS_CS_RTABLE_SEND::kDbIDFieldNumber;
const int MSG_DS_CS_RTABLE_SEND::kTableNameFieldNumber;
const int MSG_DS_CS_RTABLE_SEND::kRowTableFieldNumber;
#endif  // !_MSC_VER

MSG_DS_CS_RTABLE_SEND::MSG_DS_CS_RTABLE_SEND()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MSG_DS_CS_RTABLE_SEND)
}

void MSG_DS_CS_RTABLE_SEND::InitAsDefaultInstance() {
}

MSG_DS_CS_RTABLE_SEND::MSG_DS_CS_RTABLE_SEND(const MSG_DS_CS_RTABLE_SEND& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:MSG_DS_CS_RTABLE_SEND)
}

void MSG_DS_CS_RTABLE_SEND::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  taskid_ = 0u;
  dbid_ = 0u;
  tablename_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MSG_DS_CS_RTABLE_SEND::~MSG_DS_CS_RTABLE_SEND() {
  // @@protoc_insertion_point(destructor:MSG_DS_CS_RTABLE_SEND)
  SharedDtor();
}

void MSG_DS_CS_RTABLE_SEND::SharedDtor() {
  if (tablename_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete tablename_;
  }
  if (this != default_instance_) {
  }
}

void MSG_DS_CS_RTABLE_SEND::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MSG_DS_CS_RTABLE_SEND::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MSG_DS_CS_RTABLE_SEND_descriptor_;
}

const MSG_DS_CS_RTABLE_SEND& MSG_DS_CS_RTABLE_SEND::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_MSG_5fDS_5fCS_5fRTABLE_5fSEND_2eproto();
  return *default_instance_;
}

MSG_DS_CS_RTABLE_SEND* MSG_DS_CS_RTABLE_SEND::default_instance_ = NULL;

MSG_DS_CS_RTABLE_SEND* MSG_DS_CS_RTABLE_SEND::New() const {
  return new MSG_DS_CS_RTABLE_SEND;
}

void MSG_DS_CS_RTABLE_SEND::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<MSG_DS_CS_RTABLE_SEND*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 7) {
    ZR_(taskid_, dbid_);
    if (has_tablename()) {
      if (tablename_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        tablename_->clear();
      }
    }
  }

#undef OFFSET_OF_FIELD_
#undef ZR_

  rowtable_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MSG_DS_CS_RTABLE_SEND::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MSG_DS_CS_RTABLE_SEND)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 taskID = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &taskid_)));
          set_has_taskid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_dbID;
        break;
      }

      // required uint32 dbID = 2;
      case 2: {
        if (tag == 16) {
         parse_dbID:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &dbid_)));
          set_has_dbid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_tableName;
        break;
      }

      // required string tableName = 3;
      case 3: {
        if (tag == 26) {
         parse_tableName:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_tablename()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->tablename().data(), this->tablename().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "tablename");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_rowTable;
        break;
      }

      // repeated .MSG_DS_CS_RTABLE_SEND.ROW_TABLE rowTable = 4;
      case 4: {
        if (tag == 34) {
         parse_rowTable:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_rowtable()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_rowTable;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MSG_DS_CS_RTABLE_SEND)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MSG_DS_CS_RTABLE_SEND)
  return false;
#undef DO_
}

void MSG_DS_CS_RTABLE_SEND::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MSG_DS_CS_RTABLE_SEND)
  // required uint32 taskID = 1;
  if (has_taskid()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->taskid(), output);
  }

  // required uint32 dbID = 2;
  if (has_dbid()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->dbid(), output);
  }

  // required string tableName = 3;
  if (has_tablename()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->tablename().data(), this->tablename().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "tablename");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->tablename(), output);
  }

  // repeated .MSG_DS_CS_RTABLE_SEND.ROW_TABLE rowTable = 4;
  for (int i = 0; i < this->rowtable_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->rowtable(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:MSG_DS_CS_RTABLE_SEND)
}

::google::protobuf::uint8* MSG_DS_CS_RTABLE_SEND::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:MSG_DS_CS_RTABLE_SEND)
  // required uint32 taskID = 1;
  if (has_taskid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->taskid(), target);
  }

  // required uint32 dbID = 2;
  if (has_dbid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->dbid(), target);
  }

  // required string tableName = 3;
  if (has_tablename()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->tablename().data(), this->tablename().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "tablename");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->tablename(), target);
  }

  // repeated .MSG_DS_CS_RTABLE_SEND.ROW_TABLE rowTable = 4;
  for (int i = 0; i < this->rowtable_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        4, this->rowtable(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MSG_DS_CS_RTABLE_SEND)
  return target;
}

int MSG_DS_CS_RTABLE_SEND::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 taskID = 1;
    if (has_taskid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->taskid());
    }

    // required uint32 dbID = 2;
    if (has_dbid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->dbid());
    }

    // required string tableName = 3;
    if (has_tablename()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->tablename());
    }

  }
  // repeated .MSG_DS_CS_RTABLE_SEND.ROW_TABLE rowTable = 4;
  total_size += 1 * this->rowtable_size();
  for (int i = 0; i < this->rowtable_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->rowtable(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MSG_DS_CS_RTABLE_SEND::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MSG_DS_CS_RTABLE_SEND* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MSG_DS_CS_RTABLE_SEND*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MSG_DS_CS_RTABLE_SEND::MergeFrom(const MSG_DS_CS_RTABLE_SEND& from) {
  GOOGLE_CHECK_NE(&from, this);
  rowtable_.MergeFrom(from.rowtable_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_taskid()) {
      set_taskid(from.taskid());
    }
    if (from.has_dbid()) {
      set_dbid(from.dbid());
    }
    if (from.has_tablename()) {
      set_tablename(from.tablename());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MSG_DS_CS_RTABLE_SEND::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MSG_DS_CS_RTABLE_SEND::CopyFrom(const MSG_DS_CS_RTABLE_SEND& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MSG_DS_CS_RTABLE_SEND::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  if (!::google::protobuf::internal::AllAreInitialized(this->rowtable())) return false;
  return true;
}

void MSG_DS_CS_RTABLE_SEND::Swap(MSG_DS_CS_RTABLE_SEND* other) {
  if (other != this) {
    std::swap(taskid_, other->taskid_);
    std::swap(dbid_, other->dbid_);
    std::swap(tablename_, other->tablename_);
    rowtable_.Swap(&other->rowtable_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MSG_DS_CS_RTABLE_SEND::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MSG_DS_CS_RTABLE_SEND_descriptor_;
  metadata.reflection = MSG_DS_CS_RTABLE_SEND_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
