// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MSG_DC_RA_DATABASE_INFO_GET.proto

#ifndef PROTOBUF_MSG_5fDC_5fRA_5fDATABASE_5fINFO_5fGET_2eproto__INCLUDED
#define PROTOBUF_MSG_5fDC_5fRA_5fDATABASE_5fINFO_5fGET_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "common.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MSG_5fDC_5fRA_5fDATABASE_5fINFO_5fGET_2eproto();
void protobuf_AssignDesc_MSG_5fDC_5fRA_5fDATABASE_5fINFO_5fGET_2eproto();
void protobuf_ShutdownFile_MSG_5fDC_5fRA_5fDATABASE_5fINFO_5fGET_2eproto();

class MSG_DC_RA_DATABASE_INFO_GET;
class MSG_RA_DC_DATABASE_INFO_GET_ACK;

// ===================================================================

class MSG_DC_RA_DATABASE_INFO_GET : public ::google::protobuf::Message {
 public:
  MSG_DC_RA_DATABASE_INFO_GET();
  virtual ~MSG_DC_RA_DATABASE_INFO_GET();

  MSG_DC_RA_DATABASE_INFO_GET(const MSG_DC_RA_DATABASE_INFO_GET& from);

  inline MSG_DC_RA_DATABASE_INFO_GET& operator=(const MSG_DC_RA_DATABASE_INFO_GET& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MSG_DC_RA_DATABASE_INFO_GET& default_instance();

  void Swap(MSG_DC_RA_DATABASE_INFO_GET* other);

  // implements Message ----------------------------------------------

  MSG_DC_RA_DATABASE_INFO_GET* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MSG_DC_RA_DATABASE_INFO_GET& from);
  void MergeFrom(const MSG_DC_RA_DATABASE_INFO_GET& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:MSG_DC_RA_DATABASE_INFO_GET)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_MSG_5fDC_5fRA_5fDATABASE_5fINFO_5fGET_2eproto();
  friend void protobuf_AssignDesc_MSG_5fDC_5fRA_5fDATABASE_5fINFO_5fGET_2eproto();
  friend void protobuf_ShutdownFile_MSG_5fDC_5fRA_5fDATABASE_5fINFO_5fGET_2eproto();

  void InitAsDefaultInstance();
  static MSG_DC_RA_DATABASE_INFO_GET* default_instance_;
};
// -------------------------------------------------------------------

class MSG_RA_DC_DATABASE_INFO_GET_ACK : public ::google::protobuf::Message {
 public:
  MSG_RA_DC_DATABASE_INFO_GET_ACK();
  virtual ~MSG_RA_DC_DATABASE_INFO_GET_ACK();

  MSG_RA_DC_DATABASE_INFO_GET_ACK(const MSG_RA_DC_DATABASE_INFO_GET_ACK& from);

  inline MSG_RA_DC_DATABASE_INFO_GET_ACK& operator=(const MSG_RA_DC_DATABASE_INFO_GET_ACK& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MSG_RA_DC_DATABASE_INFO_GET_ACK& default_instance();

  void Swap(MSG_RA_DC_DATABASE_INFO_GET_ACK* other);

  // implements Message ----------------------------------------------

  MSG_RA_DC_DATABASE_INFO_GET_ACK* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MSG_RA_DC_DATABASE_INFO_GET_ACK& from);
  void MergeFrom(const MSG_RA_DC_DATABASE_INFO_GET_ACK& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 statusCode = 1;
  inline bool has_statuscode() const;
  inline void clear_statuscode();
  static const int kStatusCodeFieldNumber = 1;
  inline ::google::protobuf::int32 statuscode() const;
  inline void set_statuscode(::google::protobuf::int32 value);

  // required string statusMsg = 2;
  inline bool has_statusmsg() const;
  inline void clear_statusmsg();
  static const int kStatusMsgFieldNumber = 2;
  inline const ::std::string& statusmsg() const;
  inline void set_statusmsg(const ::std::string& value);
  inline void set_statusmsg(const char* value);
  inline void set_statusmsg(const char* value, size_t size);
  inline ::std::string* mutable_statusmsg();
  inline ::std::string* release_statusmsg();
  inline void set_allocated_statusmsg(::std::string* statusmsg);

  // repeated .DATABASE_INFO dbInfo = 3;
  inline int dbinfo_size() const;
  inline void clear_dbinfo();
  static const int kDbInfoFieldNumber = 3;
  inline const ::DATABASE_INFO& dbinfo(int index) const;
  inline ::DATABASE_INFO* mutable_dbinfo(int index);
  inline ::DATABASE_INFO* add_dbinfo();
  inline const ::google::protobuf::RepeatedPtrField< ::DATABASE_INFO >&
      dbinfo() const;
  inline ::google::protobuf::RepeatedPtrField< ::DATABASE_INFO >*
      mutable_dbinfo();

  // @@protoc_insertion_point(class_scope:MSG_RA_DC_DATABASE_INFO_GET_ACK)
 private:
  inline void set_has_statuscode();
  inline void clear_has_statuscode();
  inline void set_has_statusmsg();
  inline void clear_has_statusmsg();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* statusmsg_;
  ::google::protobuf::RepeatedPtrField< ::DATABASE_INFO > dbinfo_;
  ::google::protobuf::int32 statuscode_;
  friend void  protobuf_AddDesc_MSG_5fDC_5fRA_5fDATABASE_5fINFO_5fGET_2eproto();
  friend void protobuf_AssignDesc_MSG_5fDC_5fRA_5fDATABASE_5fINFO_5fGET_2eproto();
  friend void protobuf_ShutdownFile_MSG_5fDC_5fRA_5fDATABASE_5fINFO_5fGET_2eproto();

  void InitAsDefaultInstance();
  static MSG_RA_DC_DATABASE_INFO_GET_ACK* default_instance_;
};
// ===================================================================


// ===================================================================

// MSG_DC_RA_DATABASE_INFO_GET

// -------------------------------------------------------------------

// MSG_RA_DC_DATABASE_INFO_GET_ACK

// required int32 statusCode = 1;
inline bool MSG_RA_DC_DATABASE_INFO_GET_ACK::has_statuscode() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MSG_RA_DC_DATABASE_INFO_GET_ACK::set_has_statuscode() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MSG_RA_DC_DATABASE_INFO_GET_ACK::clear_has_statuscode() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MSG_RA_DC_DATABASE_INFO_GET_ACK::clear_statuscode() {
  statuscode_ = 0;
  clear_has_statuscode();
}
inline ::google::protobuf::int32 MSG_RA_DC_DATABASE_INFO_GET_ACK::statuscode() const {
  // @@protoc_insertion_point(field_get:MSG_RA_DC_DATABASE_INFO_GET_ACK.statusCode)
  return statuscode_;
}
inline void MSG_RA_DC_DATABASE_INFO_GET_ACK::set_statuscode(::google::protobuf::int32 value) {
  set_has_statuscode();
  statuscode_ = value;
  // @@protoc_insertion_point(field_set:MSG_RA_DC_DATABASE_INFO_GET_ACK.statusCode)
}

// required string statusMsg = 2;
inline bool MSG_RA_DC_DATABASE_INFO_GET_ACK::has_statusmsg() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MSG_RA_DC_DATABASE_INFO_GET_ACK::set_has_statusmsg() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MSG_RA_DC_DATABASE_INFO_GET_ACK::clear_has_statusmsg() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MSG_RA_DC_DATABASE_INFO_GET_ACK::clear_statusmsg() {
  if (statusmsg_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    statusmsg_->clear();
  }
  clear_has_statusmsg();
}
inline const ::std::string& MSG_RA_DC_DATABASE_INFO_GET_ACK::statusmsg() const {
  // @@protoc_insertion_point(field_get:MSG_RA_DC_DATABASE_INFO_GET_ACK.statusMsg)
  return *statusmsg_;
}
inline void MSG_RA_DC_DATABASE_INFO_GET_ACK::set_statusmsg(const ::std::string& value) {
  set_has_statusmsg();
  if (statusmsg_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    statusmsg_ = new ::std::string;
  }
  statusmsg_->assign(value);
  // @@protoc_insertion_point(field_set:MSG_RA_DC_DATABASE_INFO_GET_ACK.statusMsg)
}
inline void MSG_RA_DC_DATABASE_INFO_GET_ACK::set_statusmsg(const char* value) {
  set_has_statusmsg();
  if (statusmsg_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    statusmsg_ = new ::std::string;
  }
  statusmsg_->assign(value);
  // @@protoc_insertion_point(field_set_char:MSG_RA_DC_DATABASE_INFO_GET_ACK.statusMsg)
}
inline void MSG_RA_DC_DATABASE_INFO_GET_ACK::set_statusmsg(const char* value, size_t size) {
  set_has_statusmsg();
  if (statusmsg_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    statusmsg_ = new ::std::string;
  }
  statusmsg_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:MSG_RA_DC_DATABASE_INFO_GET_ACK.statusMsg)
}
inline ::std::string* MSG_RA_DC_DATABASE_INFO_GET_ACK::mutable_statusmsg() {
  set_has_statusmsg();
  if (statusmsg_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    statusmsg_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:MSG_RA_DC_DATABASE_INFO_GET_ACK.statusMsg)
  return statusmsg_;
}
inline ::std::string* MSG_RA_DC_DATABASE_INFO_GET_ACK::release_statusmsg() {
  clear_has_statusmsg();
  if (statusmsg_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = statusmsg_;
    statusmsg_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void MSG_RA_DC_DATABASE_INFO_GET_ACK::set_allocated_statusmsg(::std::string* statusmsg) {
  if (statusmsg_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete statusmsg_;
  }
  if (statusmsg) {
    set_has_statusmsg();
    statusmsg_ = statusmsg;
  } else {
    clear_has_statusmsg();
    statusmsg_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:MSG_RA_DC_DATABASE_INFO_GET_ACK.statusMsg)
}

// repeated .DATABASE_INFO dbInfo = 3;
inline int MSG_RA_DC_DATABASE_INFO_GET_ACK::dbinfo_size() const {
  return dbinfo_.size();
}
inline void MSG_RA_DC_DATABASE_INFO_GET_ACK::clear_dbinfo() {
  dbinfo_.Clear();
}
inline const ::DATABASE_INFO& MSG_RA_DC_DATABASE_INFO_GET_ACK::dbinfo(int index) const {
  // @@protoc_insertion_point(field_get:MSG_RA_DC_DATABASE_INFO_GET_ACK.dbInfo)
  return dbinfo_.Get(index);
}
inline ::DATABASE_INFO* MSG_RA_DC_DATABASE_INFO_GET_ACK::mutable_dbinfo(int index) {
  // @@protoc_insertion_point(field_mutable:MSG_RA_DC_DATABASE_INFO_GET_ACK.dbInfo)
  return dbinfo_.Mutable(index);
}
inline ::DATABASE_INFO* MSG_RA_DC_DATABASE_INFO_GET_ACK::add_dbinfo() {
  // @@protoc_insertion_point(field_add:MSG_RA_DC_DATABASE_INFO_GET_ACK.dbInfo)
  return dbinfo_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::DATABASE_INFO >&
MSG_RA_DC_DATABASE_INFO_GET_ACK::dbinfo() const {
  // @@protoc_insertion_point(field_list:MSG_RA_DC_DATABASE_INFO_GET_ACK.dbInfo)
  return dbinfo_;
}
inline ::google::protobuf::RepeatedPtrField< ::DATABASE_INFO >*
MSG_RA_DC_DATABASE_INFO_GET_ACK::mutable_dbinfo() {
  // @@protoc_insertion_point(field_mutable_list:MSG_RA_DC_DATABASE_INFO_GET_ACK.dbInfo)
  return &dbinfo_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MSG_5fDC_5fRA_5fDATABASE_5fINFO_5fGET_2eproto__INCLUDED
